export enum BookGenre {
  FICTION = "FICTION",
  NON_FICTION = "NON_FICTION",
  MYSTERY = "MYSTERY",
  SCI_FI = "SCIENCE_FICTION",
  FANTASY = "FANTASY",
  BIOGRAPHY = "BIOGRAPHY",
  HISTORY = "HISTORICAL",
  ROMANCE = "ROMANCE",
  SELF_HELP = "SELF_HELP",
  CHILDREN = "CHILDREN",
}

export enum BookFormat {
  HARDCOVER = "HARDCOVER",
  PAPERBACK = "PAPERBACK",
  EBOOK = "EBOOK",
  AUDIOBOOK = "AUDIO",
}

export enum BookStatus {
  AVAILABLE = "AVAILABLE",
  ARCHIVED = "ARCHIVED",
  OUT_OF_STOCK = "OUT_OF_STOCK",
  DISCONTINUED = "DISCONTINUED",
  PREORDER = "PREORDER",
}
